{
	"version": 1523414000,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/platform-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/char3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/titletextspr-sheet0.png",
		"media/bit quest.m4a",
		"media/bit quest.ogg",
		"media/blip stream.m4a",
		"media/blip stream.ogg",
		"media/pixelland.m4a",
		"media/pixelland.ogg",
		"media/bit quest_short.m4a",
		"media/bit quest_short.ogg",
		"media/blip stream_short.m4a",
		"media/blip stream_short.ogg",
		"media/pixelland_short.m4a",
		"media/pixelland_short.ogg",
		"media/overworld.m4a",
		"media/overworld.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"bazookaregular.eot",
		"bazookaregular.svg",
		"bazookaregular.ttf",
		"bazookaregular.woff",
		"stylesheet.css"
	]
}